// Sodium/calcium/potassium/magnesium (mg) per serving for the seeded foods,
// keyed by exact food name. Same caveat as the other seed files — researched
// approximations, not lab-measured. Merged onto the base seed entries in
// seed.ts rather than inlined, to keep the base files scannable.

export type Micronutrients = {
  sodiumMg?: number;
  calciumMg?: number;
  potassiumMg?: number;
  magnesiumMg?: number;
};

export const micronutrients: Record<string, Micronutrients> = {
  // --- Indian foods ---
  "Roti / Chapati (whole wheat)": { sodiumMg: 3, calciumMg: 10, potassiumMg: 90, magnesiumMg: 30 },
  "Naan (plain)": { sodiumMg: 300, calciumMg: 40, potassiumMg: 100, magnesiumMg: 25 },
  "Paratha (plain)": { sodiumMg: 150, calciumMg: 15, potassiumMg: 90, magnesiumMg: 25 },
  "Aloo Paratha": { sodiumMg: 250, calciumMg: 25, potassiumMg: 300, magnesiumMg: 30 },
  "Puri": { sodiumMg: 100, calciumMg: 8, potassiumMg: 40, magnesiumMg: 12 },
  "Bhatura": { sodiumMg: 200, calciumMg: 15, potassiumMg: 80, magnesiumMg: 15 },

  "Steamed White Rice": { sodiumMg: 2, calciumMg: 15, potassiumMg: 55, magnesiumMg: 18 },
  "Steamed Brown Rice": { sodiumMg: 3, calciumMg: 15, potassiumMg: 130, magnesiumMg: 65 },
  "Jeera Rice": { sodiumMg: 300, calciumMg: 20, potassiumMg: 80, magnesiumMg: 25 },
  "Vegetable Pulao": { sodiumMg: 400, calciumMg: 40, potassiumMg: 220, magnesiumMg: 40 },
  "Chicken Biryani": { sodiumMg: 600, calciumMg: 50, potassiumMg: 350, magnesiumMg: 50 },
  "Veg Biryani": { sodiumMg: 500, calciumMg: 45, potassiumMg: 280, magnesiumMg: 45 },
  "Curd Rice": { sodiumMg: 150, calciumMg: 150, potassiumMg: 200, magnesiumMg: 30 },
  "Lemon Rice": { sodiumMg: 350, calciumMg: 25, potassiumMg: 120, magnesiumMg: 30 },

  "Toor Dal (cooked)": { sodiumMg: 200, calciumMg: 30, potassiumMg: 400, magnesiumMg: 45 },
  "Moong Dal (cooked)": { sodiumMg: 180, calciumMg: 35, potassiumMg: 380, magnesiumMg: 42 },
  "Chana Dal (cooked)": { sodiumMg: 200, calciumMg: 40, potassiumMg: 420, magnesiumMg: 55 },
  "Dal Makhani": { sodiumMg: 450, calciumMg: 100, potassiumMg: 400, magnesiumMg: 50 },
  "Rajma (kidney bean curry)": { sodiumMg: 400, calciumMg: 70, potassiumMg: 500, magnesiumMg: 60 },
  "Chole (chickpea curry)": { sodiumMg: 450, calciumMg: 80, potassiumMg: 480, magnesiumMg: 65 },
  "Sambar": { sodiumMg: 350, calciumMg: 40, potassiumMg: 300, magnesiumMg: 35 },
  "Butter Chicken": { sodiumMg: 700, calciumMg: 80, potassiumMg: 400, magnesiumMg: 40 },
  "Chicken Curry": { sodiumMg: 500, calciumMg: 40, potassiumMg: 450, magnesiumMg: 45 },
  "Egg Curry": { sodiumMg: 450, calciumMg: 90, potassiumMg: 280, magnesiumMg: 30 },
  "Fish Curry": { sodiumMg: 500, calciumMg: 60, potassiumMg: 500, magnesiumMg: 55 },
  "Mutton Curry": { sodiumMg: 500, calciumMg: 40, potassiumMg: 450, magnesiumMg: 45 },

  "Paneer Butter Masala": { sodiumMg: 550, calciumMg: 350, potassiumMg: 300, magnesiumMg: 35 },
  "Palak Paneer": { sodiumMg: 450, calciumMg: 400, potassiumMg: 450, magnesiumMg: 60 },
  "Shahi Paneer": { sodiumMg: 500, calciumMg: 380, potassiumMg: 280, magnesiumMg: 35 },
  "Kadai Paneer": { sodiumMg: 480, calciumMg: 370, potassiumMg: 320, magnesiumMg: 40 },
  "Raw Paneer": { sodiumMg: 20, calciumMg: 480, potassiumMg: 150, magnesiumMg: 30 },
  "Aloo Gobi": { sodiumMg: 350, calciumMg: 40, potassiumMg: 500, magnesiumMg: 35 },
  "Aloo Jeera": { sodiumMg: 300, calciumMg: 25, potassiumMg: 550, magnesiumMg: 35 },
  "Bhindi Masala (okra)": { sodiumMg: 350, calciumMg: 90, potassiumMg: 400, magnesiumMg: 60 },
  "Baingan Bharta": { sodiumMg: 400, calciumMg: 30, potassiumMg: 350, magnesiumMg: 30 },
  "Mixed Vegetable Curry": { sodiumMg: 400, calciumMg: 60, potassiumMg: 400, magnesiumMg: 40 },
  "Palak (spinach, cooked)": { sodiumMg: 120, calciumMg: 150, potassiumMg: 550, magnesiumMg: 90 },
  "Cabbage Sabzi": { sodiumMg: 250, calciumMg: 60, potassiumMg: 250, magnesiumMg: 20 },

  "Idli": { sodiumMg: 200, calciumMg: 15, potassiumMg: 60, magnesiumMg: 20 },
  "Plain Dosa": { sodiumMg: 250, calciumMg: 15, potassiumMg: 70, magnesiumMg: 20 },
  "Masala Dosa": { sodiumMg: 400, calciumMg: 30, potassiumMg: 250, magnesiumMg: 35 },
  "Uttapam": { sodiumMg: 300, calciumMg: 20, potassiumMg: 100, magnesiumMg: 25 },
  "Medu Vada": { sodiumMg: 350, calciumMg: 30, potassiumMg: 150, magnesiumMg: 30 },
  "Upma": { sodiumMg: 400, calciumMg: 25, potassiumMg: 150, magnesiumMg: 35 },
  "Pongal": { sodiumMg: 350, calciumMg: 30, potassiumMg: 130, magnesiumMg: 35 },

  "Poha": { sodiumMg: 350, calciumMg: 25, potassiumMg: 200, magnesiumMg: 30 },
  "Besan Chilla": { sodiumMg: 300, calciumMg: 25, potassiumMg: 150, magnesiumMg: 40 },
  "Samosa": { sodiumMg: 300, calciumMg: 15, potassiumMg: 150, magnesiumMg: 15 },
  "Kachori": { sodiumMg: 280, calciumMg: 12, potassiumMg: 130, magnesiumMg: 15 },
  "Pakora / Bhajiya (mixed veg)": { sodiumMg: 350, calciumMg: 30, potassiumMg: 200, magnesiumMg: 25 },
  "Dhokla": { sodiumMg: 300, calciumMg: 20, potassiumMg: 100, magnesiumMg: 20 },
  "Pav Bhaji": { sodiumMg: 700, calciumMg: 60, potassiumMg: 600, magnesiumMg: 50 },
  "Vada Pav": { sodiumMg: 400, calciumMg: 20, potassiumMg: 250, magnesiumMg: 25 },
  "Chana Chaat": { sodiumMg: 300, calciumMg: 60, potassiumMg: 350, magnesiumMg: 50 },
  "Bhel Puri": { sodiumMg: 450, calciumMg: 30, potassiumMg: 250, magnesiumMg: 25 },
  "Sev Puri": { sodiumMg: 500, calciumMg: 25, potassiumMg: 220, magnesiumMg: 20 },
  "Pani Puri": { sodiumMg: 400, calciumMg: 15, potassiumMg: 200, magnesiumMg: 15 },

  "Boiled Egg": { sodiumMg: 62, calciumMg: 25, potassiumMg: 63, magnesiumMg: 6 },
  "Omelette (2 eggs)": { sodiumMg: 200, calciumMg: 55, potassiumMg: 130, magnesiumMg: 12 },
  "Egg Bhurji": { sodiumMg: 350, calciumMg: 60, potassiumMg: 200, magnesiumMg: 20 },
  "Tandoori Chicken": { sodiumMg: 400, calciumMg: 20, potassiumMg: 400, magnesiumMg: 40 },
  "Chicken Tikka": { sodiumMg: 380, calciumMg: 20, potassiumMg: 380, magnesiumMg: 38 },
  "Chicken 65": { sodiumMg: 450, calciumMg: 25, potassiumMg: 350, magnesiumMg: 35 },

  "Plain Curd / Yogurt": { sodiumMg: 45, calciumMg: 120, potassiumMg: 155, magnesiumMg: 12 },
  "Buttermilk (Chaas)": { sodiumMg: 150, calciumMg: 150, potassiumMg: 200, magnesiumMg: 15 },
  "Raita": { sodiumMg: 100, calciumMg: 100, potassiumMg: 130, magnesiumMg: 12 },
  "Ghee": { sodiumMg: 0, calciumMg: 1, potassiumMg: 1, magnesiumMg: 0 },
  "Milk (whole)": { sodiumMg: 100, calciumMg: 300, potassiumMg: 375, magnesiumMg: 30 },
  "Chai (with milk & sugar)": { sodiumMg: 30, calciumMg: 90, potassiumMg: 110, magnesiumMg: 10 },
  "Filter Coffee (with milk & sugar)": { sodiumMg: 30, calciumMg: 90, potassiumMg: 110, magnesiumMg: 10 },

  "Gulab Jamun": { sodiumMg: 30, calciumMg: 40, potassiumMg: 60, magnesiumMg: 8 },
  "Rasgulla": { sodiumMg: 20, calciumMg: 35, potassiumMg: 50, magnesiumMg: 6 },
  "Jalebi": { sodiumMg: 10, calciumMg: 10, potassiumMg: 15, magnesiumMg: 3 },
  "Kheer": { sodiumMg: 60, calciumMg: 150, potassiumMg: 200, magnesiumMg: 20 },
  "Barfi": { sodiumMg: 20, calciumMg: 60, potassiumMg: 60, magnesiumMg: 10 },

  "Cooked Chickpeas (plain)": { sodiumMg: 6, calciumMg: 49, potassiumMg: 291, magnesiumMg: 48 },
  "Cooked Kidney Beans (plain)": { sodiumMg: 2, calciumMg: 28, potassiumMg: 358, magnesiumMg: 45 },
  "Sprouted Moong (raw)": { sodiumMg: 5, calciumMg: 30, potassiumMg: 150, magnesiumMg: 40 },
  "Peanuts (roasted)": { sodiumMg: 3, calciumMg: 20, potassiumMg: 200, magnesiumMg: 50 },
  "Almonds": { sodiumMg: 0.3, calciumMg: 27, potassiumMg: 73, magnesiumMg: 27 },

  // --- Generic foods ---
  "Apple": { sodiumMg: 2, calciumMg: 11, potassiumMg: 214, magnesiumMg: 9 },
  "Banana": { sodiumMg: 1, calciumMg: 6, potassiumMg: 430, magnesiumMg: 32 },
  "Orange": { sodiumMg: 0, calciumMg: 52, potassiumMg: 235, magnesiumMg: 13 },
  "Mango": { sodiumMg: 3, calciumMg: 18, potassiumMg: 277, magnesiumMg: 15 },
  "Grapes": { sodiumMg: 2, calciumMg: 10, potassiumMg: 191, magnesiumMg: 7 },
  "Watermelon": { sodiumMg: 2, calciumMg: 11, potassiumMg: 170, magnesiumMg: 15 },
  "Papaya": { sodiumMg: 5, calciumMg: 30, potassiumMg: 300, magnesiumMg: 15 },
  "Pineapple": { sodiumMg: 1, calciumMg: 13, potassiumMg: 109, magnesiumMg: 12 },
  "Pomegranate": { sodiumMg: 3, calciumMg: 10, potassiumMg: 236, magnesiumMg: 12 },
  "Guava": { sodiumMg: 1, calciumMg: 10, potassiumMg: 209, magnesiumMg: 11 },
  "Pear": { sodiumMg: 2, calciumMg: 16, potassiumMg: 215, magnesiumMg: 12 },
  "Strawberries": { sodiumMg: 1, calciumMg: 16, potassiumMg: 153, magnesiumMg: 13 },
  "Blueberries": { sodiumMg: 1, calciumMg: 6, potassiumMg: 77, magnesiumMg: 6 },
  "Kiwi": { sodiumMg: 2, calciumMg: 24, potassiumMg: 217, magnesiumMg: 12 },
  "Peach": { sodiumMg: 0, calciumMg: 9, potassiumMg: 285, magnesiumMg: 14 },
  "Plum": { sodiumMg: 0, calciumMg: 4, potassiumMg: 105, magnesiumMg: 5 },
  "Cherries": { sodiumMg: 0, calciumMg: 13, potassiumMg: 222, magnesiumMg: 11 },
  "Dates (dried)": { sodiumMg: 0.5, calciumMg: 16, potassiumMg: 167, magnesiumMg: 11 },
  "Raisins": { sodiumMg: 4, calciumMg: 15, potassiumMg: 250, magnesiumMg: 11 },
  "Fig (dried)": { sodiumMg: 4, calciumMg: 68, potassiumMg: 272, magnesiumMg: 27 },
  "Avocado": { sodiumMg: 7, calciumMg: 12, potassiumMg: 485, magnesiumMg: 29 },
  "Coconut (fresh)": { sodiumMg: 6, calciumMg: 3, potassiumMg: 110, magnesiumMg: 8 },
  "Muskmelon / Cantaloupe": { sodiumMg: 24, calciumMg: 14, potassiumMg: 320, magnesiumMg: 15 },

  "Tomato": { sodiumMg: 5, calciumMg: 10, potassiumMg: 237, magnesiumMg: 11 },
  "Onion": { sodiumMg: 4, calciumMg: 23, potassiumMg: 146, magnesiumMg: 10 },
  "Potato (boiled)": { sodiumMg: 6, calciumMg: 8, potassiumMg: 425, magnesiumMg: 27 },
  "Sweet Potato (boiled)": { sodiumMg: 42, calciumMg: 38, potassiumMg: 337, magnesiumMg: 27 },
  "Carrot": { sodiumMg: 69, calciumMg: 33, potassiumMg: 320, magnesiumMg: 12 },
  "Cucumber": { sodiumMg: 2, calciumMg: 16, potassiumMg: 147, magnesiumMg: 13 },
  "Broccoli": { sodiumMg: 40, calciumMg: 40, potassiumMg: 293, magnesiumMg: 21 },
  "Cauliflower": { sodiumMg: 15, calciumMg: 16, potassiumMg: 142, magnesiumMg: 9 },
  "Spinach (raw)": { sodiumMg: 79, calciumMg: 99, potassiumMg: 558, magnesiumMg: 79 },
  "Bell Pepper / Capsicum": { sodiumMg: 4, calciumMg: 10, potassiumMg: 211, magnesiumMg: 12 },
  "Green Peas": { sodiumMg: 5, calciumMg: 27, potassiumMg: 244, magnesiumMg: 33 },
  "Cabbage (raw)": { sodiumMg: 18, calciumMg: 40, potassiumMg: 170, magnesiumMg: 12 },
  "Lettuce": { sodiumMg: 5, calciumMg: 18, potassiumMg: 97, magnesiumMg: 7 },
  "Mushroom": { sodiumMg: 5, calciumMg: 3, potassiumMg: 356, magnesiumMg: 11 },
  "Beetroot": { sodiumMg: 77, calciumMg: 16, potassiumMg: 305, magnesiumMg: 23 },
  "Radish": { sodiumMg: 21, calciumMg: 25, potassiumMg: 233, magnesiumMg: 10 },
  "Garlic": { sodiumMg: 1, calciumMg: 16, potassiumMg: 40, magnesiumMg: 2 },
  "Ginger": { sodiumMg: 1, calciumMg: 2, potassiumMg: 42, magnesiumMg: 4 },
  "Corn (boiled)": { sodiumMg: 15, calciumMg: 2, potassiumMg: 218, magnesiumMg: 26 },
  "Zucchini": { sodiumMg: 5, calciumMg: 16, potassiumMg: 261, magnesiumMg: 18 },
  "Green Beans": { sodiumMg: 3, calciumMg: 37, potassiumMg: 209, magnesiumMg: 25 },
  "Bottle Gourd (Lauki)": { sodiumMg: 2, calciumMg: 20, potassiumMg: 150, magnesiumMg: 11 },
  "Bitter Gourd (Karela)": { sodiumMg: 5, calciumMg: 19, potassiumMg: 296, magnesiumMg: 17 },
  "Drumstick (Moringa)": { sodiumMg: 42, calciumMg: 30, potassiumMg: 461, magnesiumMg: 45 },

  "Walnuts": { sodiumMg: 0.2, calciumMg: 10, potassiumMg: 44, magnesiumMg: 16 },
  "Cashews": { sodiumMg: 1, calciumMg: 4, potassiumMg: 56, magnesiumMg: 26 },
  "Pistachios": { sodiumMg: 0, calciumMg: 11, potassiumMg: 100, magnesiumMg: 12 },
  "Peanut Butter": { sodiumMg: 75, calciumMg: 7, potassiumMg: 105, magnesiumMg: 25 },
  "Sunflower Seeds": { sodiumMg: 2, calciumMg: 11, potassiumMg: 100, magnesiumMg: 51 },
  "Pumpkin Seeds": { sodiumMg: 2, calciumMg: 7, potassiumMg: 108, magnesiumMg: 74 },
  "Chia Seeds": { sodiumMg: 6, calciumMg: 95, potassiumMg: 61, magnesiumMg: 50 },
  "Flax Seeds": { sodiumMg: 4, calciumMg: 35, potassiumMg: 61, magnesiumMg: 55 },
  "Sesame Seeds": { sodiumMg: 2, calciumMg: 146, potassiumMg: 70, magnesiumMg: 53 },
  "Dried Coconut (desiccated)": { sodiumMg: 4, calciumMg: 4, potassiumMg: 68, magnesiumMg: 13 },

  "Cheddar Cheese": { sodiumMg: 186, calciumMg: 216, potassiumMg: 30, magnesiumMg: 8 },
  "Mozzarella Cheese": { sodiumMg: 155, calciumMg: 147, potassiumMg: 6, magnesiumMg: 3 },
  "Greek Yogurt (plain)": { sodiumMg: 55, calciumMg: 165, potassiumMg: 195, magnesiumMg: 15 },
  "Butter": { sodiumMg: 41, calciumMg: 1, potassiumMg: 1, magnesiumMg: 0 },
  "Skimmed Milk": { sodiumMg: 130, calciumMg: 350, potassiumMg: 500, magnesiumMg: 30 },
  "Egg White": { sodiumMg: 55, calciumMg: 2, potassiumMg: 54, magnesiumMg: 4 },

  "Chicken Breast (grilled, skinless)": { sodiumMg: 74, calciumMg: 15, potassiumMg: 256, magnesiumMg: 29 },
  "Chicken Thigh (cooked, skinless)": { sodiumMg: 90, calciumMg: 12, potassiumMg: 240, magnesiumMg: 24 },
  "Turkey Breast (cooked)": { sodiumMg: 55, calciumMg: 11, potassiumMg: 250, magnesiumMg: 27 },
  "Beef (lean, cooked)": { sodiumMg: 60, calciumMg: 12, potassiumMg: 318, magnesiumMg: 21 },
  "Pork Chop (cooked)": { sodiumMg: 55, calciumMg: 15, potassiumMg: 350, magnesiumMg: 25 },
  "Salmon (cooked)": { sodiumMg: 59, calciumMg: 9, potassiumMg: 384, magnesiumMg: 27 },
  "Tuna (canned in water)": { sodiumMg: 247, calciumMg: 11, potassiumMg: 237, magnesiumMg: 29 },
  "Shrimp / Prawns (cooked)": { sodiumMg: 111, calciumMg: 70, potassiumMg: 145, magnesiumMg: 39 },
  "Tilapia (cooked)": { sodiumMg: 56, calciumMg: 14, potassiumMg: 380, magnesiumMg: 34 },
  "Mutton / Lamb (cooked, plain)": { sodiumMg: 72, calciumMg: 17, potassiumMg: 310, magnesiumMg: 23 },

  "Oats (cooked)": { sodiumMg: 4, calciumMg: 42, potassiumMg: 218, magnesiumMg: 63 },
  "Quinoa (cooked)": { sodiumMg: 8, calciumMg: 23, potassiumMg: 258, magnesiumMg: 89 },
  "White Bread": { sodiumMg: 130, calciumMg: 40, potassiumMg: 35, magnesiumMg: 6 },
  "Whole Wheat Bread": { sodiumMg: 130, calciumMg: 20, potassiumMg: 55, magnesiumMg: 15 },
  "Cornflakes": { sodiumMg: 200, calciumMg: 3, potassiumMg: 30, magnesiumMg: 8 },
  "Muesli": { sodiumMg: 30, calciumMg: 40, potassiumMg: 220, magnesiumMg: 55 },
  "Pasta (cooked, plain)": { sodiumMg: 2, calciumMg: 11, potassiumMg: 63, magnesiumMg: 27 },
  "Vermicelli (cooked, plain)": { sodiumMg: 3, calciumMg: 10, potassiumMg: 55, magnesiumMg: 20 },

  "Black Beans (cooked)": { sodiumMg: 1, calciumMg: 27, potassiumMg: 355, magnesiumMg: 70 },
  "Lentils (cooked, generic)": { sodiumMg: 2, calciumMg: 19, potassiumMg: 369, magnesiumMg: 36 },
  "Soybeans (cooked)": { sodiumMg: 2, calciumMg: 102, potassiumMg: 515, magnesiumMg: 86 },
  "Tofu (firm)": { sodiumMg: 7, calciumMg: 350, potassiumMg: 121, magnesiumMg: 30 },
  "Green Gram Whole (Moong, boiled)": { sodiumMg: 4, calciumMg: 27, potassiumMg: 266, magnesiumMg: 48 },
  "Black Chickpeas (Kala Chana, boiled)": { sodiumMg: 6, calciumMg: 49, potassiumMg: 291, magnesiumMg: 48 },

  "Olive Oil": { sodiumMg: 0, calciumMg: 0, potassiumMg: 0, magnesiumMg: 0 },
  "Sunflower Oil": { sodiumMg: 0, calciumMg: 0, potassiumMg: 0, magnesiumMg: 0 },
  "Mustard Oil": { sodiumMg: 0, calciumMg: 0, potassiumMg: 0, magnesiumMg: 0 },
  "Coconut Oil": { sodiumMg: 0, calciumMg: 0, potassiumMg: 0, magnesiumMg: 0 },

  "Potato Chips": { sodiumMg: 180, calciumMg: 6, potassiumMg: 360, magnesiumMg: 20 },
  "Digestive Biscuit": { sodiumMg: 140, calciumMg: 20, potassiumMg: 60, magnesiumMg: 8 },
  "Cream Cracker": { sodiumMg: 200, calciumMg: 15, potassiumMg: 40, magnesiumMg: 6 },
  "Dark Chocolate (70%+)": { sodiumMg: 2, calciumMg: 27, potassiumMg: 175, magnesiumMg: 45 },
  "Milk Chocolate": { sodiumMg: 20, calciumMg: 50, potassiumMg: 100, magnesiumMg: 15 },
  "Whey Protein Shake (1 scoop, water)": { sodiumMg: 100, calciumMg: 120, potassiumMg: 180, magnesiumMg: 20 },
  "Granola Bar": { sodiumMg: 65, calciumMg: 20, potassiumMg: 90, magnesiumMg: 20 },

  "Black Coffee (no sugar)": { sodiumMg: 3, calciumMg: 3, potassiumMg: 60, magnesiumMg: 6 },
  "Green Tea": { sodiumMg: 1, calciumMg: 0, potassiumMg: 10, magnesiumMg: 1 },
  "Orange Juice": { sodiumMg: 2, calciumMg: 20, potassiumMg: 400, magnesiumMg: 22 },
  "Coconut Water": { sodiumMg: 262, calciumMg: 60, potassiumMg: 625, magnesiumMg: 60 },
  "Cola / Soda": { sodiumMg: 10, calciumMg: 0, potassiumMg: 0, magnesiumMg: 0 },
  "Beer": { sodiumMg: 15, calciumMg: 15, potassiumMg: 90, magnesiumMg: 22 },
  "Red Wine": { sodiumMg: 6, calciumMg: 12, potassiumMg: 190, magnesiumMg: 18 },
  "Whiskey (neat)": { sodiumMg: 0, calciumMg: 0, potassiumMg: 0, magnesiumMg: 0 },
};
